- name: installation de l'instance cloud test_app_david
  hosts: all
  become: yes
  become_method: sudo

  tasks:

    - name: installation des librairies et packages ubuntu...
      apt:
        name:
          - libxml2-dev
          - libncurses5-dev
          - libtinfo-dev
          - zlib1g-dev
          - libbz2-dev
          - liblzma-dev
          - libcurl4-openssl-dev
          - samtools
          - bedtools
          - hisat2
          - igv
          - python3-matplotlib
          - python-htseq
          - libboost-iostreams1.74.0
          - libssl-dev
          - build-essential
          - python3-dev
          # - python-numphy
          - python-pysam-tests
          - python-htseq
          - unzip
          - r-base
          - r-base-dev
          - bowtie2
          - fastqc
          - cutadapt
          - vsearch
          - hmmer
        state: present
        update_cache: yes


    - name: installation de quelques packages R
      command: >
        /usr/bin/Rscript --slave --no-save --no-restore-history
        -e "install.packages(pkgs='{{ item }}', repos=c('https://pbil.univ-lyon1.fr/CRAN/'))"
      with_items:
        - BiocManager

    - name: installation de modules bioconductor
      command: >
        /usr/bin/Rscript --slave --no-save --no-restore-history
        -e "BiocManager::install(c('{{ item }}'))"
      with_items:
        - dada2

    - name: installation de obitools4
      shell: |
        curl -sL https://metabarcoding.org/obitools4/install.sh | bash -

    - name: installation de BBMap
      ansible.builtin.unarchive:
        src: BBMap_39.01.tar.gz
        dest: /usr/local

